
spring:
  cloud:
    config:
      server:
        git:
          uri: http://cyview@aps-drones.com:7990/bitbucket/scm/cyv/microservice-configuration.git
          username: katstudz
          password: 1a8hkonik
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8010/eureka/